### ISSUE TITLE
distcc fails to distribute due to x86_64-linux-gnu-gcc not being on whitelist

### ISSUE THREAD

**Issue by LarBob** [distcc/distcc#301]
I believe this is due to symlinks but I have indeed run update-distcc-symlinks. I had to edit the script to set the cross directory to the normal gcc directory as I'm not cross compiling currently.

**Comment by shawnl** [comment]
I wrote that script on Debian so it SHOULD work there.

**Comment by LarBob** [comment]
/usr/bin/x86_64-linux-gnu-gcc
provided by gcc package
Testing on debian 9 latest (9.5.0)

**Comment by shawnl** [comment]
Are you using the update-distcc-symlinks script that is perl and shipped
with the Debian package, or the new python update-distcc-symlinks?

**Comment by LarBob** [comment]
The new one. I compiled distcc 3.3.2.


On Aug 6, 2018, at 7:54 AM, Shawn Landden <notifications@github.com<mailto:notifications@github.com>> wrote:

Are you using the update-distcc-symlinks script that is perl and shipped
with the Debian package, or the new python update-distcc-symlinks?

**Comment by shawnl** [comment]
WTF, and works based on the filelist here: https://packages.debian.org/stretch/amd64/gcc-6/filelist

with line 35 of the script:   consider_gcc("%(gnu_host)s-" % vars(), "")

you probably screwed up the script when you modified it.

**Comment by LarBob** [comment]
It had an error before I modified it due to it not finding the cross stuff. All I did when I modified it was change where it looked for the cross GCC toolchain, nothing else.

Sent from my iPhone

On Aug 6, 2018, at 8:41 AM, Shawn Landden <notifications@github.com<mailto:notifications@github.com>> wrote:


WTF, and works based on the filelist here: https://packages.debian.org/stretch/amd64/gcc-6/filelist

with line 35 of the script: consider_gcc("%(gnu_host)s-" % vars(), "")

you probably screwed up the script when you modified it.

**Comment by shawnl** [comment]
what does the script output?

I should probably catch that error. I will do this tonight.

**Comment by shawnl** [comment]
I pushed a new version that catches some errors. Can you try that version?

**Comment by LarBob** [comment]
It appears that it is now working!
```
 distcc -v
Using built-in specs.
COLLECT_GCC=x86_64-linux-gnu-gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/6/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 6.3.0-18+deb9u1' --with-bugurl=file:///usr/share/doc/gcc-6/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-6 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-6-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-6-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-6-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1)
```
Thank you! However, I still can't get it to work properly. I start getting spammed with this, though I have everything set up correctly (as far as my knowledge goes, obviously it's not correct).
```
  CC      fs/ext4/inline.o
distcc[1807] (dcc_readx) ERROR: unexpected eof on fd5
distcc[1807] (dcc_r_token_int) ERROR: read failed while waiting for token "DONE"
distcc[1807] (dcc_r_result_header) ERROR: server provided no answer. Is the server configured to allow access from your IP address? Is the server performing authentication and your client isn't? Does the server have the compiler installed? Is the server configured to access the compiler?
  CC      net/802/fddi.o
  CC      arch/x86/video/fbdev.o
  CC      net/wireless/core.o
  CC      net/packet/af_packet.o
distcc[1807] Warning: failed to distribute net/sched/sch_generic.c to 192.168.0.80:3632,lzo,cpp, running locally instead
distcc[1895] (dcc_readx) ERROR: unexpected eof on fd5
distcc[1895] (dcc_r_token_int) ERROR: read failed while waiting for token "DONE"
distcc[1895] (dcc_r_result_header) ERROR: server provided no answer. Is the server configured to allow access from your IP address? Is the server performing authentication and your client isn't? Does the server have the compiler installed? Is the server configured to access the compiler?
distcc[1895] Warning: failed to distribute arch/x86/lib/msr-smp.c to 192.168.0.80:3632,lzo,cpp, running locally instead
distcc[1814] (dcc_readx) ERROR: unexpected eof on fd5
distcc[1814] (dcc_r_token_int) ERROR: read failed while waiting for token "DONE"
distcc[1814] (dcc_r_result_header) ERROR: server provided no answer. Is the server configured to allow access from your IP address? Is the server performing authentication and your client isn't? Does the server have the compiler installed? Is the server configured to access the compiler?
distcc[1814] Warning: failed to distribute net/sched/sch_api.c to 192.168.0.80:3632,lzo,cpp, running locally instead
distcc[1894] (dcc_readx) ERROR: unexpected eof on fd5
distcc[1894] (dcc_r_token_int) ERROR: read failed while waiting for token "DONE"
distcc[1894] (dcc_r_result_header) ERROR: server provided no answer. Is the server configured to allow access from your IP address? Is the server performing authentication and your client isn't? Does the server have the compiler installed? Is the server configured to access the compiler?
distcc[1894] Warning: failed to distribute net/dns_resolver/dns_key.c to 192.168.0.81:3632,lzo,cpp, running locally instead
```
I am starting the distccd daemon like this
`distccd --daemon --allow 192.168.0.0/24 --port 3632 --listen 192.168.0.80`
on the first server and this
`distccd --daemon --allow 192.168.0.0/16 --port 3632 --listen 192.168.0.81`
on the second.

I have them specified like this
`export DISTCC_HOSTS="192.168.0.80:3632,lzo,cpp 192.168.0.81:3632,lzo,cpp"`
Thanks for any assistance.

**Comment by shawnl** [comment]
try running the server with --no-defach --log-stderr and see what it tells you,

**Comment by shawnl** [comment]
and --log-level info

**Comment by shawnl** [comment]
--log-level debug

**Comment by LarBob** [comment]
It's due to a whitelist issue.

```
distccd[1259] (dcc_check_compiler_masq) /usr/bin/x86_64-linux-gnu-gcc is a safe symlink to gcc-6
distccd[1259] (dcc_check_compiler_whitelist) CRITICAL! x86_64-linux-gnu-gcc not in /usr/local/lib/distcc whitelist.
```
I did not build it with auth/whitelist

**Comment by shawnl** [comment]
Master should not have this problem.

**Comment by shawnl** [comment]
The whitelist is necessary for security. I am working on getting TLS to into distcc so that this would be unnecessary, but it requires some patches to to libraries to use public keys rfc 7250 to make the experience better.

**Comment by LarBob** [comment]
I am using master

**Comment by shawnl** [comment]
did update-distcc-symlinks create /usr/lib/distcc/x86_64-linux-gnu-gcc ?

**Comment by LarBob** [comment]
```
larbob@uno:~$ ls /usr/lib/distcc
c++      c99-gcc  clang-3.8    gcc                     x86_64-linux-gnu-gcc
c89      cc       clang++-3.8  gcc-6                   x86_64-linux-gnu-gcc-6
c89-gcc  clang    g++          x86_64-linux-gnu-g++
c99      clang++  g++-6        x86_64-linux-gnu-g++-6
```

**Comment by shawnl** [comment]
Ok I will look into this when I get home from work this evening.

**Comment by shawnl** [comment]
Ok, I just pushed a patch to fix the problem, my bad. I was testing with a differn't configuration.

This was a regression introduced by 07c1eaa4c1c95 (which was a pull request). If you experience it as fixed I will release a new version with the fix.

**Comment by shawnl** [comment]
* bb4d613c08eeb267

**Comment by LarBob** [comment]
Okay, compiled from latest commit and it's working. Only problem is that it isn't really using much cpu % during compilation. When running pump make -j48 CC=distcc it's working but using very little of the cpus. 

![image](https://user-images.githubusercontent.com/5503528/43815842-a1036392-9a9f-11e8-8353-2ebab41116eb.png)

This is across a gigabit LAN.

**Comment by shawnl** [comment]
You need to specify your parallelism in your DISTCC_HOSTS specs

`export DISTCC_HOSTS="192.168.0.80:3632,lzo,cpp/32 192.168.0.81:3632,lzo,cpp/16"`

for example

**Comment by shawnl** [comment]
You really don't need pump  mode for so few hosts, and especially when you arn't compiling C++

**Comment by shawnl** [comment]
Also, you can specify localhost in DISTCC_HOSTS

**Comment by LarBob** [comment]
Specifying the parallelism didn't help with the CPU utilization.
Pretty much same results even with this
```
echo $DISTCC_HOSTS
192.168.0.80:3632,lzo,cpp/24 192.168.0.81:3632,lzo,cpp/24
```

**Comment by shawnl** [comment]
Hmmm maybe you can see what is going on with distccmon.

**Comment by shawnl** [comment]
Also try without pump mode. Could be bug #16

**Comment by LarBob** [comment]
I have tried with and without pump mode.

On Aug 7, 2018, at 11:41 PM, Shawn Landden <notifications@github.com<mailto:notifications@github.com>> wrote:

Hmmm maybe you can see what is going on with distccmon.

**Comment by shawnl** [comment]
Did you remove ",cpp" from DISTCC_HOSTC when you tried without pump mode?

**Comment by LarBob** [comment]
Results from that:
![image](https://user-images.githubusercontent.com/5503528/43929752-46ca76c0-9c04-11e8-833b-ed5f22ae4e28.png)

**Comment by shawnl** [comment]
Try using DISTCC_VERBOSE=1 on the client side to see what is going on.

**Comment by shawnl** [comment]
closing as works for me. Please reopen when you get more information.

**Comment by mihirpatel89** [comment]
how was this issue resolved? i'm using the latest copy and still seeing following error: (dcc_r_result_header) ERROR: server provided no answer. Is the server configured to allow access from your IP address? Is the server performing authentication and your client isn't? Does the server have the compiler installed? Is the server configured to access the compiler?

**Comment by shawnl** [comment]
Perhaps we need to clean up the ugly way that GCC cross-compiles by normalizing the names and removing the vendor part.
